# Generated by Django 6.0.3 on 2026-07-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('fathers_name', models.CharField(max_length=30)),
            ],
        ),
    ]
